### ISSUE TITLE
module signing required in ubuntu16

### ISSUE THREAD

**Issue by elitestar** [psankar/simplefs#7]
I am getting tainted kernel message on ubuntu 16. Does it mean that without signing kernel module I cannot load kernel module ?
I checked signing process docs but those are not easy to follow. Is there any workarounds to load kernel module without signing in ubuntu16?

**Comment by psankar** [comment]
Of course the kernel will crib about tainted :) It is expected because we are installing a module that is not supported by the operating system vendor. However, that should not cause any issue when you do insmod or modprobe. Do you get any error ?

To know more about taintedness see: https://www.novell.com/support/kb/doc.php?id=3582750 

I have done the entire development on openSUSE with the kernel-devel pattern installed. Ubuntu may also have some such devel pattern which you may need to enable/install to allow you to insmod kernel modules. Best of luck.

**Comment by psankar** [comment]
@elitestar Are you still having problems during modprobe/insmod ? Shall I close the bug if not ?

**Comment by elitestar** [comment]
you are right, insmod is working
